count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/2_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/3_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/4_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/5_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/6_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/7_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/8_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/9_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/10_100_10.query -i=5
count -data=/media/marc/mimicIII.csv -query=/media/marc/gpu-counter/queries/11_100_10.query -i=5
